=== jeremybahadirli/aircraft-simulator/src/config/schemas/config.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "config.schema.json",
	"title": "Aircraft Simulator Config",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"simSettings",
		"viewSettings",
		"atmosphere",
		"aircraftList",
		"stats",
		"proximities"
	],
	"properties": {
		"simSettings": { "$ref": "#/definitions/simSettings" },
		"viewSettings": { "$ref": "#/definitions/viewSettings" },
		"atmosphere": { "$ref": "#/definitions/atmosphere" },
		"aircraftList": {
			"type": "array",
			"markdownDescription": "Configures the list of aircraft.\n\nEach aircraft has a CID, callsign, position, direction, altitude, speed, fourth line, and display options. CID, callsign, and fourth line may be omitted and they'll be randomly generated. There are multiple ways to define direction and speed:\n\n- **Direction:** `heading`, `track`, or `directFix`, where `directFix` is a position on the map.\n- **Speed:** `tas`, `ias`, or `mach`.",
			"items": { "$ref": "#/definitions/aircraft" }
		},
		"stats": { "$ref": "./shared-config.schema.json#/definitions/stats" },
		"proximities": {
			"$ref": "./shared-config.schema.json#/definitions/proximities"
		}
	},
	"definitions": {
		"simSettings": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"mode",
				"playbackSpeed",
				"secondsPerUpdate",
				"startTimeMins",
				"numHistories"
			],
			"properties": {
				"mode": {
					"markdownDescription": "Simulator mode.\n\n- `normal`: Uses the aircraft list and other settings defined in `config.json`.\n- `separation_practice`: Separation Practice mode. Generates random aircraft and uses settings defined in `separation-practice-config.json`.\n- `auto_position`: Automatically positions Aircraft 1 south of Aircraft 0 such that they will pass at 5 NM separation. Normally, place Aircraft 0 at `(0, 0)` on a heading and Aircraft 1 at `(0, 0)` on a 360 track.",
					"type": "string",
					"enum": ["normal", "separation_practice", "auto_position"],
					"default": "normal"
				},
				"playbackSpeed": {
					"$ref": "./shared-config.schema.json#/definitions/playbackSpeed"
				},
				"secondsPerUpdate": {
					"$ref": "./shared-config.schema.json#/definitions/secondsPerUpdate"
				},
				"startTimeMins": {
					"markdownDescription": "Time at the beginning of the simulation in minutes.",
					"type": "number",
					"default": 0
				},
				"numHistories": {
					"$ref": "./shared-config.schema.json#/definitions/numHistories"
				}
			}
		},
		"viewSettings": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"vRange",
				"statsDecimalPlaces",
				"proximityDecimalPlaces"
			],
			"properties": {
				"vRange": {
					"$ref": "./shared-config.schema.json#/definitions/vRange"
				},
				"statsDecimalPlaces": {
					"$ref": "./shared-config.schema.json#/definitions/statsDecimalPlaces"
				},
				"proximityDecimalPlaces": {
					"$ref": "./shared-config.schema.json#/definitions/proximityDecimalPlaces"
				}
			}
		},
		"atmosphere": {
			"type": "object",
			"markdownDescription": "Configures the atmosphere.\n\nSea level temperature affects how ias and mach change with altitude. Currently, all altitudes are treated as flight levels, so sea level pressure has no effect.",
			"additionalProperties": false,
			"required": ["wind", "seaLevelTemp", "seaLevelPressure"],
			"properties": {
				"wind": {
					"type": "object",
					"additionalProperties": false,
					"required": ["from", "speed"],
					"properties": {
						"from": {
							"$ref": "#/definitions/direction",
							"markdownDescription": "Direction from which wind is coming in degrees."
						},
						"speed": {
							"type": "number",
							"markdownDescription": "Speed of wind in knots.",
							"default": 0
						}
					},
					"default": { "from": 360, "speed": 0 }
				},
				"seaLevelTemp": {
					"type": "number",
					"markdownDescription": "Sea level temperature in ºC. Standard atmosphere is 15.",
					"minimum": -100,
					"maximum": 60,
					"default": 15
				},
				"seaLevelPressure": {
					"type": "number",
					"markdownDescription": "Sea level pressure in inHg. Standard atmosphere is 29.92.",
					"minimum": 27,
					"maximum": 33,
					"default": 29.92
				}
			}
		},
		"aircraft": {
			"type": "object",
			"additionalProperties": false,
			"required": ["position", "alt", "display"],
			"properties": {
				"cid": {
					"$ref": "./shared-config.schema.json#/definitions/cid"
				},
				"callsign": {
					"$ref": "./shared-config.schema.json#/definitions/callsign"
				},
				"position": {
					"$ref": "./shared-config.schema.json#/definitions/position"
				},
				"heading": {
					"$ref": "#/definitions/direction"
				},
				"track": {
					"$ref": "#/definitions/direction"
				},
				"directFix": {
					"$ref": "./shared-config.schema.json#/definitions/position"
				},
				"alt": {
					"type": "number",
					"markdownDescription": "Altitude in hundreds of feet MSL."
				},
				"tas": {
					"type": "number",
					"minimum": 0
				},
				"ias": {
					"type": "number",
					"minimum": 0
				},
				"mach": {
					"type": "number",
					"minimum": 0,
					"exclusiveMaximum": 1
				},
				"fourthLine": {
					"type": "string",
					"pattern": "^[A-Z0-9+-]{0,8}$",
					"default": "KDFW"
				},
				"display": { "$ref": "#/definitions/aircraftDisplay" }
			},
			"allOf": [
				{
					"oneOf": [
						{ "required": ["heading"] },
						{ "required": ["track"] },
						{ "required": ["directFix"] }
					]
				},
				{
					"oneOf": [
						{ "required": ["tas"] },
						{ "required": ["ias"] },
						{ "required": ["mach"] }
					]
				}
			]
		},
		"aircraftDisplay": {
			"type": "object",
			"markdownDescription": "Data block display options. All of these are optional.\n\n- `color`: JavaScript color string.\n- `halo`: `true` or `false`.\n- `haloRadiusNm`: Radius of halo in NM.\n- `showDatablock`: `true` or `false`.\n- `datablockSlot`: Numpad direction of data block.",
			"additionalProperties": false,
			"properties": {
				"color": {
					"type": "string",
					"markdownDescription": "Must be a valid JavaScript color string. Ex:\n\n- `red`\n- `#00ff00`\n- `rgb(0, 0, 255)`",
					"default": "#FF0000"
				},
				"halo": { "type": "boolean" },
				"haloRadiusNm": {
					"type": "number",
					"exclusiveMinimum": 0,
					"default": 3
				},
				"showDatablock": { "type": "boolean" },
				"datablockSlot": {
					"type": "integer",
					"enum": [1, 2, 3, 4, 6, 7, 8, 9]
				}
			}
		},
		"direction": {
			"type": "number",
			"exclusiveMinimum": 0,
			"maximum": 360,
			"default": 360
		}
	}
}

=== jeremybahadirli/aircraft-simulator/src/config/default-config.json
{
	"simSettings": {
		"mode": "normal",
		"playbackSpeed": 1,
		"secondsPerUpdate": 12,
		"startTimeMins": 0,
		"numHistories": 3
	},
	"viewSettings": {
		"vRange": 100,
		"statsDecimalPlaces": 0,
		"proximityDecimalPlaces": 1
	},
	"atmosphere": {
		"wind": { "from": 360, "speed": 0 },
		"seaLevelTemp": 15,
		"seaLevelPressure": 29.92
	},
	"aircraftList": [
		{
			"callsign": "N737KG",
			"position": { "x": 0, "y": 10 },
			"track": 180,
			"alt": 200,
			"tas": 300,
			"display": {}
		},
		{
			"position": { "r": 100, "d": 5 },
			"directFix": { "x": 0, "y": 0 },
			"alt": 200,
			"mach": 0.79,
			"display": {
				"halo": true,
				"datablockSlot": 8
			}
		}
	],
	"stats": [{ "flid": "N737KG" }],
	"proximities": [{ "flid1": "N737KG", "index2": 2 }]
}
