=== jeremybahadirli/aircraft-simulator/src/config/schemas/separation-practice-config.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "separation-practice-config.schema.json",
	"title": "Aircraft Simulator Separation Practice Config",
	"type": "object",
	"additionalProperties": false,
	"required": [
		"simSettings",
		"viewSettings",
		"separationPracticeSettings",
		"stats",
		"proximities"
	],
	"properties": {
		"simSettings": {
			"$ref": "#/definitions/simSettings"
		},
		"viewSettings": {
			"$ref": "#/definitions/viewSettings"
		},
		"separationPracticeSettings": {
			"$ref": "#/definitions/separationPracticeSettings"
		},
		"stats": { "$ref": "./shared-config.schema.json#/definitions/stats" },
		"proximities": {
			"$ref": "./shared-config.schema.json#/definitions/proximities"
		}
	},
	"definitions": {
		"simSettings": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"playbackSpeed",
				"secondsPerUpdate"
			],
			"properties": {
				"playbackSpeed": {
					"$ref": "./shared-config.schema.json#/definitions/playbackSpeed"
				},
				"secondsPerUpdate": {
					"$ref": "./shared-config.schema.json#/definitions/secondsPerUpdate"
				}
			}
		},
		"viewSettings": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"vRange",
				"statsDecimalPlaces",
				"proximityDecimalPlaces"
			],
			"properties": {
				"vRange": {
					"$ref": "./shared-config.schema.json#/definitions/vRange"
				},
				"statsDecimalPlaces": {
					"$ref": "./shared-config.schema.json#/definitions/statsDecimalPlaces"
				},
				"proximityDecimalPlaces": {
					"$ref": "./shared-config.schema.json#/definitions/proximityDecimalPlaces"
				}
			}
		},
		"separationPracticeSettings": {
			"type": "object",
			"additionalProperties": false,
			"required": [
				"startTimeRange",
				"minSeparationRange",
				"leadSpeedRange",
				"angleRange",
				"speedDifferenceRange"
			],
			"properties": {
				"startTimeRange": {
					"type": "object",
					"markdownDescription": "Range of possible start times of the simulation in minutes. Time 0 is the time of closest proximity. Therefore, start times should be negative.\n\nThe value is randomly chosen between the min and max.",
					"additionalProperties": false,
					"required": ["min", "max"],
					"properties": {
						"min": {
							"type": "number",
							"minimum": -20,
							"maximum": -1
						},
						"max": {
							"type": "number",
							"minimum": -20,
							"maximum": -1
						}
					}
				},
				"minSeparationRange": {
					"type": "object",
					"markdownDescription": "Range of possible closest proximities of the aircraft in NM.\n\nThe value is randomly chosen between the min and max.",
					"additionalProperties": false,
					"required": ["min", "max"],
					"properties": {
						"min": {
							"type": "number",
							"minimum": 0,
							"maximum": 10
						},
						"max": {
							"type": "number",
							"minimum": 0,
							"maximum": 10
						}
					}
				},
				"leadSpeedRange": {
					"type": "object",
					"markdownDescription": "Range of possible speeds for the lead aircraft in TAS.\n\nThe value is randomly chosen between the min and max.",
					"additionalProperties": false,
					"required": ["min", "max"],
					"properties": {
						"min": {
							"type": "number",
							"minimum": 0
						},
						"max": {
							"type": "number",
							"minimum": 0
						}
					}
				},
				"angleRange": {
					"type": "object",
					"markdownDescription": "Range of possible intercept angles of the aircraft in degrees.\n\nThe value is randomly chosen between the min and max.",
					"additionalProperties": false,
					"required": ["min", "max"],
					"properties": {
						"min": {
							"type": "number",
							"minimum": 0,
							"exclusiveMaximum": 360
						},
						"max": {
							"type": "number",
							"minimum": 0,
							"exclusiveMaximum": 360
						}
					}
				},
				"speedDifferenceRange": {
					"type": "object",
					"markdownDescription": "Range of possible speed differences between the lead and trailing aircraft in knots. Negative means faster in back, positive means faster in front.\n\nThe value is randomly chosen between the min and max.",
					"additionalProperties": false,
					"required": ["min", "max"],
					"properties": {
						"min": {
							"type": "number"
						},
						"max": {
							"type": "number"
						}
					}
				}
			}
		}
	}
}

=== jeremybahadirli/aircraft-simulator/src/config/default-separation-practice-config.json
{
	"simSettings": {
		"playbackSpeed": 1,
		"secondsPerUpdate": 12
	},
	"viewSettings": {
		"vRange": 100,
		"statsDecimalPlaces": 0,
		"proximityDecimalPlaces": 1
	},

	"separationPracticeSettings": {
		"startTimeRange": {
			"min": -6,
			"max": -8
		},
		"minSeparationRange": {
			"min": 4.5,
			"max": 5.5
		},
		"leadSpeedRange": {
			"min": 300,
			"max": 600
		},
		"angleRange": {
			"min": 15,
			"max": 135
		},
		"speedDifferenceRange": {
			"min": -60,
			"max": 60
		}
	},

	"stats": [
		{ "index": 0, "label": "Front Stats" },
		{ "index": 1, "label": "Back Stats" }
	],

	"proximities": [
		{
			"index1": 0,
			"position": { "x": 0, "y": 0 },
			"label": "Front CRR"
		},
		{
			"index1": 1,
			"position": { "x": 0, "y": 0 },
			"label": "Back CRR"
		},
		{
			"index1": 0,
			"index2": 1,
			"label": "Separation"
		}
	]
}
